#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
IOS_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
REPO_ROOT=$(CDPATH= cd -- "$IOS_ROOT/../.." && pwd)
ENV_FILE="${ENV_FILE:-$REPO_ROOT/.env.local}"
OUTPUT_FILE="${OUTPUT_FILE:-$IOS_ROOT/Config/Local.xcconfig}"

if [ ! -f "$ENV_FILE" ]; then
    echo "warning: Env file not found: $ENV_FILE"
    exit 0
fi

read_env_value() {
    key="$1"
    awk -v key="$key" '
        /^[[:space:]]*#/ || /^[[:space:]]*$/ { next }
        {
            line = $0
            sub(/^[[:space:]]*export[[:space:]]+/, "", line)
            split(line, parts, "=")
            name = parts[1]
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", name)
            if (name != key) { next }
            value = substr(line, index(line, "=") + 1)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", value)
            if ((value ~ /^".*"$/) || (value ~ /^'\''.*'\''$/)) {
                value = substr(value, 2, length(value) - 2)
            }
            print value
            exit
        }
    ' "$ENV_FILE"
}

xcconfig_value() {
    printf '%s' "$1" | sed 's#://#:/$()/#g'
}

supabase_url=$(read_env_value EXPO_PUBLIC_SUPABASE_URL)
if [ -z "$supabase_url" ]; then
    supabase_url=$(read_env_value NEXT_PUBLIC_SUPABASE_URL)
fi

supabase_anon_key=$(read_env_value EXPO_PUBLIC_SUPABASE_ANON_KEY)
if [ -z "$supabase_anon_key" ]; then
    supabase_anon_key=$(read_env_value NEXT_PUBLIC_SUPABASE_ANON_KEY)
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"
{
    printf '// Generated by Scripts/sync-env-xcconfig.sh from %s\n' "$ENV_FILE"
    printf '// Do not commit this file.\n'
    printf 'EXPO_PUBLIC_SUPABASE_URL = %s\n' "$(xcconfig_value "$supabase_url")"
    printf 'EXPO_PUBLIC_SUPABASE_ANON_KEY = %s\n' "$(xcconfig_value "$supabase_anon_key")"
} > "$OUTPUT_FILE"
